# Generated by Django 3.1.12 on 2021-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210703_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                max_length=50, null=True, verbose_name="User Country"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
