# Generated by Django 3.1.12 on 2021-07-24 05:53

import bizwallet.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210724_0653'),
        ('users', '0003_auto_20210723_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to=bizwallet.users.models.kin_image)),
                ('gender', models.CharField(blank=True, choices=[('', 'Gender'), ('Male', 'MALE'), ('Female', 'FEMALE')], max_length=7, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_no', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=600, null=True, verbose_name='Residntial Address')),
            ],
            options={
                'verbose_name': 'Kin',
                'verbose_name_plural': 'Kins',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='Plan Slug')),
                ('invest', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='How much do you want to start with')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired')], default='pending', max_length=100, no_check_for_status=True)),
                ('approved', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.services')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(choices=[('', 'SELECT BANK'), ('ACCESS BANK PLC', 'ACCESS BANK PLC'), ('CITIBANK NIG. PLC', 'CITIBANK NIG. PLC'), ('ECOBANK NIG. PLC', 'ECOBANK NIG. PLC'), ('FIDELITY BANK PLC', 'FIDELITY BANK PLC'), ('FIRST BANK NIG. LTD', 'FIRST BANK NIG. LTD'), ('FIRST CITY MONUMENT BANK PLC', 'FIRST CITY MONUMENT BANK PLC'), ('GLOBUS BANK LTD', 'GLOBUS BANK LTD'), ('GUARANTY TRUST BANK PLC', 'GUARANTY TRUST BANK PLC'), ('HERITAGE BANKING COMPANY LTD', 'HERITAGE BANKING COMPANY LTD'), ('KEYSTONE BANK', 'KEYSTONE BANK'), ('POLARIS BANK', 'POLARIS BANK'), ('PROVIDUS BANK', 'PROVIDUS BANK'), ('STANBIC IBTC BANK LTD', 'STANBIC IBTC BANK LTD'), ('STANDARD CHARTERED BANK NIG. LTD', 'STANDARD CHARTERED BANK NIG. LTD'), ('STERLING BANK PLC', 'STERLING BANK PLC'), ('SUNTRUST BANK NIG. PLC', 'SUNTRUST BANK NIG. PLC'), ('TITAN TRUST BANK LTD', 'TITAN TRUST BANK LTD'), ('UNION BANK OF NIG. PLC', 'UNION BANK OF NIG. PLC'), ('UNITED BANK FOR AFRICA PLC', 'UNITED BANK FOR AFRICA PLC'), ('UNITY BANK PLC', 'UNITY BANK PLC'), ('WEMA BANK PLC', 'WEMA BANK PLC'), ('ZENITH BANK PLC', 'ZENITH BANK PLC')], max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bvn',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Bank Verification Number (BVN)'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='user',
            name='office_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to=bizwallet.users.models.profile_image),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nextofkin', to=settings.AUTH_USER_MODEL),
        ),
    ]
