# Generated by Django 3.1.12 on 2021-07-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210724_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enrollment Plan Title')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='1.00 means 100%, 0.50 mean 50%', max_digits=3, null=True, verbose_name='Plan Percentage')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='Plan Slug')),
                ('duration', models.CharField(blank=True, choices=[('0', '0'), ('28', '28'), ('64', '64'), ('112', '112'), ('168', '168'), ('336', '336'), ('672', '672')], default='168', max_length=4, null=True, verbose_name='Duration')),
                ('invest', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='How much for this plan')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired')], default='pending', max_length=100, no_check_for_status=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bill', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Amount To pay')),
                ('started_on', models.DateTimeField(auto_now=True, verbose_name='Plan Started on')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userplan', to='users.enrollmentplan'),
        ),
    ]
