# Generated by Django 3.1.12 on 2021-07-27 21:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210724_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'managed': True, 'ordering': ['-created', '-modified'], 'verbose_name': 'Subscribe', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='enrollmentplan',
            name='invest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: ₦50,000.00, max-amount: ₦2,000,000.00', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50000.00')), django.core.validators.MaxValueValidator(Decimal('2000000.00'))], verbose_name='Minimum & Maximum Investment Amount'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='bill',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: ₦50,000.00, max-amount: ₦2,000,000.00', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50000.00')), django.core.validators.MaxValueValidator(Decimal('2000000.00'))], verbose_name='Minimum & Maximum Investment Amount'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('testimony', models.CharField(blank=True, max_length=400, null=True, verbose_name='Testimony')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertestimonial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
    ]
