# Generated by Django 3.1.12 on 2021-07-05 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210704_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fieldworkerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_field_worker',
            field=models.BooleanField(default=True, verbose_name='Are you a field worker'),
        ),
    ]
