# Generated by Django 3.1.12 on 2021-07-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210727_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
