# Generated by Django 3.1.12 on 2021-07-12 12:31

import bizwallet.users.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210705_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/team/7.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to=bizwallet.users.models.profile_image),
        ),
    ]
