# Generated by Django 3.1.12 on 2021-08-18 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='ver_expired',
            field=models.DateField(default=datetime.date(2021, 8, 21)),
        ),
    ]
