# Generated by Django 3.1.12 on 2021-08-21 10:16

import bizwallet.users.models
import datetime
from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210818_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Membership Feature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[2287, 1127], upload_to=bizwallet.users.models.plan_image),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ver_expired',
            field=models.DateField(default=datetime.date(2021, 8, 24)),
        ),
        migrations.AddField(
            model_name='membership',
            name='features',
            field=models.ManyToManyField(null=True, to='users.MembershipFeature'),
        ),
    ]
