# Generated by Django 3.1.12 on 2021-08-22 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_balhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='ver_expired',
            field=models.DateField(default=datetime.date(2021, 8, 25)),
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wd_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Failed', 'Failed')], default='Pending', max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_withdrawals', to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
