# Generated by Django 3.1.12 on 2021-08-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210822_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Located City'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='User Country'),
        ),
    ]
