# Generated by Django 3.1.12 on 2021-08-24 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210822_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='ver_expired',
            field=models.DateField(default=datetime.date(2021, 8, 27)),
        ),
    ]
