# Generated by Django 3.1.12 on 2021-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210825_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='bank_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Bank ID'),
        ),
        migrations.AddField(
            model_name='banks',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Bank Country'),
        ),
        migrations.AddField(
            model_name='banks',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Bank currency'),
        ),
    ]
