# Generated by Django 3.1.12 on 2021-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210825_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='bank_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bank ID'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Bank Name'),
        ),
    ]
