# Generated by Django 3.1.12 on 2021-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210825_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
