# Generated by Django 3.1.12 on 2021-08-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210825_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbank', to='users.banks'),
        ),
    ]
