# Generated by Django 3.1.12 on 2021-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210825_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='bank_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Bank Code'),
        ),
    ]
