# Generated by Django 3.1.12 on 2021-08-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210825_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bvn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Bank Verification Number (BVN)'),
        ),
    ]
