# Generated by Django 3.1.12 on 2021-08-25 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210825_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_withdrawals', to='users.profile'),
        ),
        migrations.CreateModel(
            name='TopWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference_code', models.CharField(blank=True, default='', max_length=100)),
                ('access_code', models.CharField(blank=True, default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_topup', to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
