# Generated by Django 3.1.12 on 2021-08-26 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210825_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_newsletter',
            field=models.BooleanField(default=True, verbose_name='Allow Newsletter Emailing'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_subscription',
            field=models.BooleanField(default=True, verbose_name='Allow Email Subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_transaction',
            field=models.BooleanField(default=True, verbose_name='Allow Transaction Emailing'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ver_expired',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
    ]
