# Generated by Django 3.1.12 on 2021-08-16 13:31

import bizwallet.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pub_date', models.DateField(null=True, verbose_name='Post Published Date')),
                ('title', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Post Title')),
                ('slug', models.SlugField(blank=True, max_length=700, null=True, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Post Content')),
                ('videos', models.FileField(blank=True, null=True, upload_to=bizwallet.blog.models.blog_file_path, verbose_name='Upload Video')),
                ('url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogpost', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(help_text='Tag this item.', to='category.Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1920, 1148], upload_to=bizwallet.blog.models.post_image, verbose_name='Upload Post Image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Files',
                'verbose_name_plural': 'Post Files',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
