# Generated by Django 3.1.12 on 2021-07-13 01:01

import bizwallet.core.models
from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/team/7.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[2000, 1222], upload_to=bizwallet.core.models.services_image)),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service Title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Service Description')),
                ('active', models.BooleanField(default=False, verbose_name='Activate Services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
    ]
