# Generated by Django 3.1.12 on 2021-07-24 05:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='Service Slug'),
        ),
        migrations.CreateModel(
            name='ServicesVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service Title')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='Variation Slug')),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: ₦30,000.00, max-amount: ₦2,000,000.00', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30000.00')), django.core.validators.MaxValueValidator(Decimal('2000000.00'))], verbose_name='Minimum & Maximum Investment Amount')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='1.00 means 100%, 0.50 mean 50%', max_digits=3, null=True, verbose_name='Variation Percentage')),
                ('duration', models.CharField(blank=True, choices=[('0', '0'), ('64', '64'), ('168', '168'), ('336', '336'), ('672', '672')], default='168', max_length=4, null=True, verbose_name='Duration')),
                ('active', models.BooleanField(default=False, verbose_name='Activate Variation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicevariation', to='core.services')),
            ],
            options={
                'verbose_name': 'ServicesVariation',
                'verbose_name_plural': 'ServicesVariations',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
    ]
