# Generated by Django 3.1.12 on 2021-07-27 21:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210724_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesvariations',
            name='min_investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: ₦50,000.00, max-amount: ₦2,000,000.00', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50000.00')), django.core.validators.MaxValueValidator(Decimal('2000000.00'))], verbose_name='Minimum & Maximum Investment Amount'),
        ),
    ]
