# Generated by Django 3.2 on 2021-08-04 01:52

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210727_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Please')),
            ],
            options={
                'verbose_name': 'Email Subscriber',
                'verbose_name_plural': 'Email Subscribers',
                'ordering': ['-created', '-modified'],
                'managed': True,
            },
        ),
    ]
